name: H_Theomachy
main: septagram.Theomachy.Theomachy
version: 4.1.2
api-version: 1.14

commands:
  t:
       description: 신들의전쟁
       permission:
       usage: /<command>
  x:
       description: 신들의전쟁 타겟 등록
       permission:
       usage: /<command>